/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TypedJsWc {
    'options': any;
    'strings': string;
  }
}

declare global {


  interface HTMLTypedJsWcElement extends Components.TypedJsWc, HTMLStencilElement {}
  var HTMLTypedJsWcElement: {
    prototype: HTMLTypedJsWcElement;
    new (): HTMLTypedJsWcElement;
  };
  interface HTMLElementTagNameMap {
    'typed-js-wc': HTMLTypedJsWcElement;
  }
}

declare namespace LocalJSX {
  interface TypedJsWc extends JSXBase.HTMLAttributes<HTMLTypedJsWcElement> {
    'options'?: any;
    'strings'?: string;
  }

  interface IntrinsicElements {
    'typed-js-wc': TypedJsWc;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


